# Generated by Django 2.2.4 on 2019-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='img/default.png', upload_to='upload', verbose_name='封面'),
        ),
    ]
