# Generated by Django 2.2.4 on 2020-03-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
