# Generated by Django 2.2.4 on 2020-04-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='introduction',
        ),
    ]
