# Generated by Django 2.2.4 on 2020-04-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200414_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookk',
            name='cover',
            field=models.ImageField(upload_to='upload', verbose_name='封面'),
        ),
    ]
