# Generated by Django 2.2.4 on 2020-04-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200414_0109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookk',
            new_name='book',
        ),
    ]
